@extends('layouts.admin')

@section('title', 'Super Admin Dashboard')

@section('content')
<div class="container mx-auto px-4 py-8">
    
    <div class="mb-8">
        <h3 class="text-3xl font-bold text-gray-800">Dashboard Overview</h3>
        <p class="text-gray-500 mt-1">Welcome back, Super Admin. Here is what's happening today.</p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        
        <div class="bg-white rounded-xl shadow-sm p-6 border-l-4 border-blue-500 hover:shadow-md transition-shadow duration-300">
            <div class="flex items-center justify-between">
                <div>
                    <p class="text-xs font-bold text-gray-400 uppercase tracking-wider">Total Agents</p>
                    <h2 class="text-3xl font-bold text-gray-800 mt-1">{{ $total_agents }}</h2>
                </div>
                <div class="p-3 bg-blue-50 rounded-full text-blue-600">
                    <i class="fas fa-user-tie text-xl"></i>
                </div>
            </div>
        </div>

        <div class="bg-white rounded-xl shadow-sm p-6 border-l-4 border-green-500 hover:shadow-md transition-shadow duration-300">
            <div class="flex items-center justify-between">
                <div>
                    <p class="text-xs font-bold text-gray-400 uppercase tracking-wider">Total Students</p>
                    <h2 class="text-3xl font-bold text-gray-800 mt-1">{{ $total_students }}</h2>
                </div>
                <div class="p-3 bg-green-50 rounded-full text-green-600">
                    <i class="fas fa-user-graduate text-xl"></i>
                </div>
            </div>
        </div>

        <div class="bg-white rounded-xl shadow-sm p-6 border-l-4 border-purple-500 hover:shadow-md transition-shadow duration-300">
            <div class="flex items-center justify-between">
                <div>
                    <p class="text-xs font-bold text-gray-400 uppercase tracking-wider">Admission Forms</p>
                    <h2 class="text-3xl font-bold text-gray-800 mt-1">{{ $total_forms }}</h2>
                </div>
                <div class="p-3 bg-purple-50 rounded-full text-purple-600">
                    <i class="fas fa-file-alt text-xl"></i>
                </div>
            </div>
        </div>

        <div class="bg-white rounded-xl shadow-sm p-6 border-l-4 border-orange-500 hover:shadow-md transition-shadow duration-300">
            <div class="flex items-center justify-between">
                <div>
                    <p class="text-xs font-bold text-gray-400 uppercase tracking-wider">Applications</p>
                    <h2 class="text-3xl font-bold text-gray-800 mt-1">{{ $total_submissions }}</h2>
                </div>
                <div class="p-3 bg-orange-50 rounded-full text-orange-600">
                    <i class="fas fa-paper-plane text-xl"></i>
                </div>
            </div>
        </div>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        
        <div class="bg-gradient-to-br from-gray-800 to-gray-900 rounded-2xl shadow-lg p-8 text-white relative overflow-hidden">
            <div class="relative z-10">
                <div class="flex items-center space-x-3 mb-2">
                    <div class="p-2 bg-white/10 rounded-lg">
                        <i class="fas fa-wallet text-yellow-400"></i>
                    </div>
                    <span class="text-gray-300 font-medium">Total Commission</span>
                </div>
                <h2 class="text-4xl font-bold text-white tracking-tight">
                    ${{ number_format($total_commission, 2) }}
                </h2>
                <p class="text-gray-400 text-sm mt-2">Total earnings generated by agents</p>
            </div>
            <div class="absolute top-0 right-0 -mt-4 -mr-4 w-24 h-24 bg-white/5 rounded-full blur-xl"></div>
        </div>

        <div class="bg-gradient-to-br from-emerald-600 to-teal-700 rounded-2xl shadow-lg p-8 text-white relative overflow-hidden">
            <div class="relative z-10">
                <div class="flex items-center space-x-3 mb-2">
                    <div class="p-2 bg-white/10 rounded-lg">
                        <i class="fas fa-check-circle text-emerald-200"></i>
                    </div>
                    <span class="text-emerald-100 font-medium">Paid Commission</span>
                </div>
                <h2 class="text-4xl font-bold text-white tracking-tight">
                    ${{ number_format($paid_commission, 2) }}
                </h2>
                <p class="text-emerald-100 text-sm mt-2 opacity-80">Total amount disbursed to date</p>
            </div>
            <div class="absolute bottom-0 left-0 -mb-4 -ml-4 w-24 h-24 bg-black/10 rounded-full blur-xl"></div>
        </div>

    </div>

    <div class="mt-8">
        <div class="bg-white p-4 rounded-lg border border-gray-200 shadow-sm flex flex-wrap gap-4 items-center justify-between">
            <span class="text-gray-700 font-medium pl-2">Quick Actions:</span>
            <div class="flex gap-3">
                <a href="{{ route('admin.forms.create') }}" class="inline-flex items-center px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium rounded-md transition">
                    <i class="fas fa-plus mr-2"></i> New Form
                </a>
                <a href="{{ route('admin.agents.index') }}" class="inline-flex items-center px-4 py-2 bg-white border border-gray-300 hover:bg-gray-50 text-gray-700 text-sm font-medium rounded-md transition">
                    <i class="fas fa-users mr-2"></i> Manage Agents
                </a>
            </div>
        </div>
    </div>

</div>
@endsection